# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  node8:
    docker:
      - image: node:carbon
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - node-8-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - node-8-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: node-8-dependencies-{{ checksum "yarn.lock" }}

      # run tests!
      - run: yarn run lint:js
      - run: yarn test
      - run: yarn run build

  node4:
    docker:
      - image: node:argon
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - node-4-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - node-4-dependencies-

      - run: yarn install --ignore-engines

      - save_cache:
          paths:
            - node_modules
          key: node-4-dependencies-{{ checksum "yarn.lock" }}

      # run tests!
      - run: yarn run lint:js
      - run: yarn test

workflows:
  version: 2
  test-supported-node-versions:
    jobs:
      - node8
      - node4
